config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  resources :users, only: [:new, :create, :destroy, :show, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get 'sessions/new'
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  resources :tweets do
    resources :comments, only: [:create]
    resources :likes, only: %i[create destroy]
  end

  get 'likes/create'
  get 'likes/destroy'

  get '/follow/:id', to: 'follows#follow'
  delete '/follow/:id', to: 'follows#unfollow'
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :fullname, presence: true, length: { maximum: 20, minimum: 3 }
  validates :username, uniqueness: true

  has_many :tweets, dependent: :destroy, foreign_key: :author_id
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :follows, foreign_key: :follower_id
  has_many :followings, through: :follows, source: :followed_user
  has_many :received_follows, foreign_key: :followed_id, class_name: 'Follow'
  has_many :followers, through: :received_follows, source: :follower
end

app/controllers/users_controller.rb
# rubocop: disable Style/GuardClause

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all.includes(%i[comments tweets likes followings followers])
  end

  def show
    @tweets = @user.tweets
    @tweets.each { |tweet| @comment = tweet.comments }
    if current_user
      @followed = current_user.followings
      @followers = current_user.followers
    end
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :fullname)
  end
end

# rubocop: enable Style/GuardClause

app/helpers/users_helper.rb
# rubocop: disable Style/GuardClause

module UsersHelper
  def follow_unfollow
    check if current_user
  end

  def check
    if Follow.where(follower_id: current_user.id, followed_id: @user.id).exists?
      link_to('Unfollow', "/follow/#{@user.id}", method: 'delete', class: 'btn btn-danger text-white')
    elsif current_user.id != @user.id
      link_to('follow', "/follow/#{@user.id}", class: 'btn btn-primary text-white')
    end
  end

  def edit_profile_btn
    @user = User.find(params[:id])

    link_to 'Edit', edit_user_path(@user) if current_user == @user.id
  end

  def edit_tweet_btn(tweet)
    if tweet.user == current_user
      link_to edit_tweet_path(tweet), class: 'level-item' do
        raw("<span class='icon'><i class='fas fa-pencil-alt'></i></span>")
      end
    end
  end

  def delete_tweet_btn(tweet)
    if tweet.user == current_user
      link_to tweet, method: :delete, data: { confirm: 'Are you sure you want to delete this tweeet?' } do
        raw("<span class='icon'><i class='far fa-trash-alt'></i></span>")
      end
    end
  end

  def comments(tweet)
    unless @comment.empty?
      raw("<p><b>Comments:</b></p>

      <div class='border rounded p-2'>
        #{render partial: 'comments/comment', collection: tweet.comments}
      </div><br>")
    end
  end
end

# rubocop: enable Style/GuardClause

app/views/users/_form.html.erb
<div class="sign_up">
  <%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :username %>
    </div>

    <div class="form-inputs">
      <%= f.input :fullname %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-success btn-block' %>
    </div>
  <% end %>
</div>

app/views/users/_user_profile.html.erb
<nav class="right-panel panel">
  <div class="panel-block p-3">
    <article class="media d-flex align-items-center">
      <div class="media-left">
        <figure class="image">
          <div class="gravatar" style="background:transparent url(<%= gravatar_image_url('spam@spam.com'.gsub('spam', @user.username), size: 64) %>) 0px 0px no-repeat; width:64px; height:64px;"></div>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= @user.fullname.capitalize %></strong><br>
          <small>@<%= @user.username %></small><br>
        </div>
        <%= edit_profile_btn %>
        <%= follow_unfollow %>
      </div>
    </article>
  </div>
  <div class="panel-block d-flex justify-content-around mt-2">
    <div class="media d-flex justify-content-around">
      <div class="media-left d-flex flex-column align-items-center">
        <h3 class="font-weight-bold">Followers</h3>
        <p><%= @user.followers.count %></p>
      </div>

      <div class="media-left d-flex flex-column align-items-center">
        <h3 class="font-weight-bold">Following</h3>
        <p><%= @user.followings.count %></p>
      </div>

      <div class="media-left d-flex flex-column align-items-center">
        <h3 class="font-weight-bold">Tweets</h3>
        <p><%= @user.tweets.count %> </p>
      </div>
    </div>
  </div>
  <div class="media-left container mt-3">
    <h3 class="font-weight-bold">Followers:</h3>
    <% @user.followers.each do |user| %>
      <div class="panel-block">
        <article class="media d-flex align-items-center">
          <div class="media-left">
            <figure class="image is-50x50">
                <div class="gravatar image is-64x64" style="background:transparent url(<%= gravatar_image_url('spam@spam.com'.gsub('spam', user.username), size: 50) %>) 0px 0px no-repeat; width:50px; height:50px;"></div>
            </figure>
          </div>
          <div class="media-content">
            <div class="content d-flex align-items-center">
              <p>
                <strong><%= link_to user.fullname.capitalize, user %></strong> <br>
                <small>@<%= user.username %></small>
              </p>
            </div>
          </div>
        </article>
      </div>
    <% end %>
  </div>
  <div class="media-left container mt-3">
    <h3 class="font-weight-bold">Following:</h3>
    <% @user.followings.each do |user| %>
      <div class="panel-block">
        <article class="media d-flex align-items-center">
          <div class="media-left">
            <figure class="image is-50x50">
                <div class="gravatar image is-64x64" style="background:transparent url(<%= gravatar_image_url('spam@spam.com'.gsub('spam', user.username), size: 50) %>) 0px 0px no-repeat; width:50px; height:50px;"></div>
            </figure>
          </div>
          <div class="media-content">
            <div class="content d-flex align-items-center">
              <p>
                <strong><%= link_to user.fullname.capitalize, user %></strong> <br>
                <small>@<%= user.username %></small>
              </p>
            </div>
          </div>
        </article>
      </div>
    <% end %>
  </div>
</nav>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', root_path %>

app/views/users/new.html.erb
<div class="login col-6 mx-auto">

  <h1 class="mt-5 font-weight-bolder text-center">New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', users_path, class: 'btn btn-primary btn-block text-white mt-1' %>

</div>

app/views/users/show.html.erb
<div class="my-6 d-flex mr-0">
  <div class="col-4 sticky-sidebar order-2">
   <%= render 'user_profile' %>
  </div>
  <div class="col-8 panel">
    <div class="cover-img mt-2">
      <%= image_tag('bg', class: 'cover-img') %>
    </div>
    <p id="notice"><%= notice %></p>
    <div class="panel-block d-flex mt-2">
      <div class="media">
        <div class="media-left">
          <h3 class="font-weight-bold">Tweets: <%= @user.tweets.count %> </h3>
        </div>
      </div>
    </div>      

      <% @tweets.each do |tweet| %>
        <div class="box my-3">
          <article class="media">
            <div class="media-left">
              <figure class="image is-64x64">
                <div class="gravatar" style="background:transparent url(<%= gravatar_image_url('spam@spam.com'.gsub('spam', tweet.user.username), size: 64) %>) 0px 0px no-repeat; width:64px; height:64px;"></div>
              </figure>
            </div>
            <div class="media-content">
              <div class="content">
                <strong><%= link_to tweet.user.fullname, user_path(tweet.user) %> </strong><br>
                <small>@<%= tweet.user.username%></small>
              </div>
              <p><%= tweet.tweet %></p><br>
              <nav class="level">
                <div class="level-left is-mobile">
                  <%= edit_tweet_btn(tweet) %>
                  <%= delete_tweet_btn(tweet) %>
                  &nbsp;&nbsp;&nbsp;&nbsp;
                  <%= check_main(tweet) %>
                  &nbsp;&nbsp;&nbsp;&nbsp;
                  <p>Likes: <%= tweet.likes.count %> </p>
                </div>
              </nav>
              <div class='tweet-comments-section'>

                <%= comments(tweet) %>

                <%= comments_form(tweet) %>
              </div>
            </div>
          </article>
        </div>
      <% end %>

  </div>
</div>